### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by mainboarder** [tabacha/dabman-api#1]
Hi there,

thank you for your documentation, I would like to take a closer look into it, but I only get 401 Unauthorized on every endpoint.
Unfortunally I did not find any information on how to get a session. Also the Frontier Silicon Radio way of login does not work (fsapi/CREATE_SESSION?pin=<PIN> with standard 1234 as PIN) according to https://www.openhab.org/addons/bindings/frontiersiliconradio1/

**Comment by alsFC** [comment]
I got the requests working documented in this API with my MEDION WiFi Radio. However I have to pass a Basic Auth Header with every request to get it answered. To find out the Basic Auth key for my device I sniffed the traffic between the AirMusic Control App on my iPad and the device: https://apps.apple.com/de/app/airmusic-control/id848176615

**Comment by BertV1** [comment]
I can confirm this also works with the dabman i220

It's indeed necessary to acquire the authorization to be able to make the requests, which can be acquired like @alsFC said by sniffing the traffic. I did this by running the airmusic control app in an android emulator.

Thanks a lot for the documentation on the API.

**Comment by do6uk** [comment]
Is there any idea how the Auth-Code is calculated?

**Comment by Signum** [comment]
I just took the APK (Android) file of AirMusic Control and took a look at it. Hint: https://www.apkdecompilers.com/
Then I found this in the reverse-engineered source code:

    b.a.f6554g = "Basic " + Base64.encodeToString("su3g4go6sk7:ji39454xu/^".getBytes(), 2);

I already used the "Packet Capture" app on my smartphone and found the same credentials in the network traffic. Actually I wondered if the credentials are somehow magically computed from the serial number of MAC address or something. It seems that it's indeed hard-coded.

Give it a try on your radio:

    curl -H 'Authorization: Basic c3UzZzRnbzZzazc6amkzOTQ1NHh1L14=' http://…/GetSystemInfo

At least that worked on my DABMAN i450.

**Comment by mainboarder** [comment]
Wow, that works for me.
Thank you!

**Comment by tabacha** [comment]
Would be great if someone creates a pull request for this for the documentation.

**Comment by dr-ni** [comment]
ok done see pull requests

**Comment by dr-ni** [comment]
see also:
https://github.com/dr-ni/dabman-i400
